In [1]:
import tushare as ts
import pandas as pd
import time, datetime
ts.set_token('add25d81ad873db57d60c417e8e5fcad1bd6085b492979ee5821b751')
pro = ts.pro_api()

In [2]:
startdate, enddate = '20150101', '20190430'
benchmarkdf = pd.read_csv('Fund-tushare-20151231-20190331.csv')
symboldf = benchmarkdf.drop_duplicates(subset=['symbol'], keep='first')
symboldf = symboldf.sort_values('symbol', ascending=True)
symbollist = symboldf['symbol'].tolist()

In [3]:
def getdf(cc):
    df = pro.query('daily', ts_code=cc, start_date=startdate, end_date=enddate)
    df = df.drop('pre_close', axis=1, inplace=False)
    df = df.drop('change', axis=1, inplace=False)
    df = df.drop('pct_chg', axis=1, inplace=False)
    df = df.drop('vol', axis=1, inplace=False)
    df = df.drop('amount', axis=1, inplace=False)
    df = df.sort_values('trade_date', ascending=True)
    return df

def mergedf(olddf, newdf):
    df = pd.concat([olddf, newdf], axis=0, ignore_index=True)
    return df

In [4]:
sdf = pd.DataFrame(columns=['ts_code', 'trade_date', 'open', 'high', 'low', 'close'])

for s in symbollist:
    try:
        df = getdf(s)
    except:
        print('sleep for 65 seconds with ' + s)
        time.sleep(65)
        df = getdf(s)
    sdf = mergedf(sdf, df)
    print(s + '    ', end='\r')

sleep for 65 seconds with 000553.SZ

In [5]:
sdf

          ts_code trade_date   open   high    low  close
0       000001.SZ   20150105  15.99  16.28  15.60  16.02
1       000001.SZ   20150106  15.85  16.39  15.55  15.78
2       000001.SZ   20150107  15.56  15.83  15.30  15.48
3       000001.SZ   20150108  15.50  15.57  14.90  14.96
4       000001.SZ   20150109  14.90  15.87  14.71  15.08
5       000001.SZ   20150112  14.87  15.05  14.50  14.77
6       000001.SZ   20150113  14.65  14.90  14.61  14.68
7       000001.SZ   20150114  14.78  15.20  14.70  14.81
8       000001.SZ   20150115  14.85  15.35  14.71  15.35
9       000001.SZ   20150116  15.40  15.62  15.18  15.37
10      000001.SZ   20150119  14.01  14.57  13.83  13.83
11      000001.SZ   20150120  13.83  14.06  13.56  13.83
12      000001.SZ   20150121  13.88  14.60  13.75  14.42
13      000001.SZ   20150122  14.34  14.52  14.16  14.30
14      000001.SZ   20150123  14.36  14.63  14.30  14.40
15      000001.SZ   20150126  14.36  14.44  14.16  14.34
16      000001.SZ   20150127  14.35  14.37  13.83  13.99
17      000001.SZ   20150128  13.87  14.30  13.80  14.06
18      000001.SZ   20150129  13.82  14.01  13.75  13.90
19      000001.SZ   20150130  13.93  14.12  13.76  13.93
20      000001.SZ   20150202  13.60  13.80  13.55  13.63
21      000001.SZ   20150203  13.78  13.99  13.62  13.95
22      000001.SZ   20150204  14.00  14.04  13.70  13.71
23      000001.SZ   20150205  14.30  14.43  13.76  13.79
24      000001.SZ   20150206  13.69  13.95  13.40  13.51
25      000001.SZ   20150209  13.50  13.68  13.22  13.52
26      000001.SZ   20150210  13.49  13.82  13.42  13.77
27      000001.SZ   20150211  13.78  13.85  13.68  13.73
28      000001.SZ   20150212  13.75  13.90  13.62  13.86
29      000001.SZ   20150213  13.93  14.18  13.84  13.95
...           ...        ...    ...    ...    ...    ...
474778  603993.SH   20190319   4.92   4.97   4.87   4.93
474779  603993.SH   20190320   4.97   4.98   4.81   4.88
474780  603993.SH   20190321   4.88   4.94   4.85   4.87
474781  603993.SH   20190322   4.85   4.87   4.72   4.78
474782  603993.SH   20190325   4.67   4.70   4.61   4.61
474783  603993.SH   20190326   4.62   4.67   4.48   4.51
474784  603993.SH   20190327   4.53   4.56   4.43   4.48
474785  603993.SH   20190328   4.48   4.60   4.43   4.53
474786  603993.SH   20190329   4.55   4.66   4.48   4.66
474787  603993.SH   20190401   4.69   5.03   4.69   4.95
474788  603993.SH   20190402   5.00   5.15   4.88   5.03
474789  603993.SH   20190403   4.98   5.05   4.91   5.01
474790  603993.SH   20190404   5.05   5.18   5.01   5.07
474791  603993.SH   20190408   5.18   5.22   5.03   5.09
474792  603993.SH   20190409   5.07   5.07   4.89   4.96
474793  603993.SH   20190410   4.91   4.98   4.88   4.95
474794  603993.SH   20190411   4.94   5.06   4.88   4.89
474795  603993.SH   20190412   4.85   4.91   4.80   4.85
474796  603993.SH   20190415   4.94   4.97   4.84   4.85
474797  603993.SH   20190416   4.81   4.96   4.76   4.96
474798  603993.SH   20190417   4.96   4.96   4.89   4.91
474799  603993.SH   20190418   4.91   4.94   4.81   4.82
474800  603993.SH   20190419   4.79   4.85   4.77   4.85
474801  603993.SH   20190422   4.78   4.78   4.61   4.62
474802  603993.SH   20190423   4.62   4.64   4.51   4.55
474803  603993.SH   20190424   4.56   4.61   4.51   4.60
474804  603993.SH   20190425   4.59   4.60   4.45   4.45
474805  603993.SH   20190426   4.42   4.45   4.37   4.37
474806  603993.SH   20190429   4.37   4.40   4.12   4.17
474807  603993.SH   20190430   4.15   4.25   4.12   4.21

[474808 rows x 6 columns]

In [6]:
sdf.to_csv('Daily-tushare-20150101-20190430.csv')