In [1]:
import pandas as pd
import numpy as np

In [2]:
dailydf = pd.read_csv('Daily-tushare-20160101-20190430.csv')
dailydf = dailydf.drop('Unnamed: 0', axis=1, inplace=False)
indexdf = pd.read_csv('Index-tushare-20160101-20190430.csv')
indexdf = indexdf.drop('Unnamed: 0', axis=1, inplace=False)
daterange = indexdf.drop_duplicates(subset=['trade_date'], keep='first')['trade_date']

In [3]:
def decideRange(date):
    dr = daterange.values.tolist()
    while dr[-1] > date:
        dr.pop()
    return dr[-1]

In [4]:
indexdailydf = dailydf.drop_duplicates(subset=['trade_date'], keep='first')
indexdailydf = indexdailydf.drop('ts_code', axis=1, inplace=False)
indexdailydf = indexdailydf.drop('open', axis=1, inplace=False)
indexdailydf = indexdailydf.drop('high', axis=1, inplace=False)
indexdailydf = indexdailydf.drop('low', axis=1, inplace=False)
indexdailydf = indexdailydf.drop('close', axis=1, inplace=False)

In [5]:
indexnlist = []
for date in indexdailydf['trade_date']:
    weights = indexdf[indexdf['trade_date']==decideRange(date)]
    weightlist, pricelist, indexn = weights['weight'].tolist(), [], 0
    for con in weights['con_code']:
        prices = dailydf[dailydf['ts_code']==con]
        try:
            pricelist.append(prices[prices['trade_date']==date]['close'].values[0])
        except:
            pricelist.append(0)
    indexn = np.multiply(np.array(weightlist), np.array(pricelist)).sum()
    indexnlist.append(indexn)

In [6]:
indexdailydf.insert(1, 'value', indexnlist)
indexdailydf

     trade_date        value
0      20160104  1960.416800
1      20160105  1965.223300
2      20160106  1989.598800
3      20160107  1859.621200
4      20160108  1889.259400
5      20160111  1790.204100
6      20160112  1802.833200
7      20160113  1762.887300
8      20160114  1801.789000
9      20160115  1739.281500
10     20160118  1753.189900
11     20160119  1812.138100
12     20160120  1772.902100
13     20160121  1718.584000
14     20160122  1728.423400
15     20160125  1733.710600
16     20160126  1633.998700
17     20160127  1622.494200
18     20160128  1581.820700
19     20160129  1654.984290
20     20160201  1633.754210
21     20160202  1667.162470
22     20160203  1664.971990
23     20160204  1691.715850
24     20160205  1678.831680
25     20160215  1668.669530
26     20160216  1678.052570
27     20160217  1692.543000
28     20160218  1684.666560
29     20160219  1687.002510
..          ...          ...
780    20190319  5360.116248
781    20190320  5362.708011
782    20190321  5327.410520
783    20190322  5347.517192
784    20190325  5213.192918
785    20190326  5193.704759
786    20190327  5295.490567
787    20190328  5337.316612
788    20190329  5846.227340
789    20190401  5844.205630
790    20190402  5803.825100
791    20190403  5795.452890
792    20190404  5914.898420
793    20190408  6039.421030
794    20190409  6161.735920
795    20190410  6330.679510
796    20190411  6172.344250
797    20190412  6119.872190
798    20190415  6097.745700
799    20190416  6294.658600
800    20190417  6345.688120
801    20190418  6320.982580
802    20190419  6394.920790
803    20190422  6316.845730
804    20190423  6415.740030
805    20190424  6399.089190
806    20190425  6281.567240
807    20190426  6219.633900
808    20190429  6351.657660
809    20190430  6354.494490

[810 rows x 2 columns]

In [7]:
changelist = []
for i in range(0, len(indexnlist)):
    if i != 0:
        changelist.append((indexnlist[i]-indexnlist[i-1])/indexnlist[i-1])
    else:
        changelist.append(0)
indexdailydf.insert(2, 'change', changelist)
indexdailydf

     trade_date        value    change
0      20160104  1960.416800  0.000000
1      20160105  1965.223300  0.002452
2      20160106  1989.598800  0.012403
3      20160107  1859.621200 -0.065329
4      20160108  1889.259400  0.015938
5      20160111  1790.204100 -0.052431
6      20160112  1802.833200  0.007055
7      20160113  1762.887300 -0.022157
8      20160114  1801.789000  0.022067
9      20160115  1739.281500 -0.034692
10     20160118  1753.189900  0.007997
11     20160119  1812.138100  0.033623
12     20160120  1772.902100 -0.021652
13     20160121  1718.584000 -0.030638
14     20160122  1728.423400  0.005725
15     20160125  1733.710600  0.003059
16     20160126  1633.998700 -0.057514
17     20160127  1622.494200 -0.007041
18     20160128  1581.820700 -0.025069
19     20160129  1654.984290  0.046253
20     20160201  1633.754210 -0.012828
21     20160202  1667.162470  0.020449
22     20160203  1664.971990 -0.001314
23     20160204  1691.715850  0.016063
24     20160205  1678.831680 -0.007616
25     20160215  1668.669530 -0.006053
26     20160216  1678.052570  0.005623
27     20160217  1692.543000  0.008635
28     20160218  1684.666560 -0.004654
29     20160219  1687.002510  0.001387
..          ...          ...       ...
780    20190319  5360.116248 -0.013479
781    20190320  5362.708011  0.000484
782    20190321  5327.410520 -0.006582
783    20190322  5347.517192  0.003774
784    20190325  5213.192918 -0.025119
785    20190326  5193.704759 -0.003738
786    20190327  5295.490567  0.019598
787    20190328  5337.316612  0.007898
788    20190329  5846.227340  0.095350
789    20190401  5844.205630 -0.000346
790    20190402  5803.825100 -0.006909
791    20190403  5795.452890 -0.001443
792    20190404  5914.898420  0.020610
793    20190408  6039.421030  0.021052
794    20190409  6161.735920  0.020253
795    20190410  6330.679510  0.027418
796    20190411  6172.344250 -0.025011
797    20190412  6119.872190 -0.008501
798    20190415  6097.745700 -0.003616
799    20190416  6294.658600  0.032293
800    20190417  6345.688120  0.008107
801    20190418  6320.982580 -0.003893
802    20190419  6394.920790  0.011697
803    20190422  6316.845730 -0.012209
804    20190423  6415.740030  0.015656
805    20190424  6399.089190 -0.002595
806    20190425  6281.567240 -0.018365
807    20190426  6219.633900 -0.009860
808    20190429  6351.657660  0.021227
809    20190430  6354.494490  0.000447

[810 rows x 3 columns]

In [8]:
indexdailydf.to_csv('Index-Daily-20160101-20190430.csv')